GRANT USAGE ON SCHEMA rw TO rw_app;

GRANT SELECT, INSERT, UPDATE
ON ALL TABLES IN SCHEMA rw
TO rw_app;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA rw
TO rw_app;

GRANT EXECUTE
ON ALL FUNCTIONS IN SCHEMA rw
TO rw_app;